version: '3.8'

services:
  server:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_R2DBC_URL=r2dbc:postgresql://db:5432/intershop
      - SPRING_R2DBC_USERNAME=s
      - SPRING_R2DBC_PASSWORD=sa
    restart: on-failure

  db:
    image: postgres:13.7-alpine
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=s
      - POSTGRES_PASSWORD=sa
      - POSTGRES_DB=intershop
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U s -d intershop"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: