spring:
  application:
    name: intershop
  main:
    banner-mode: off

  datasource:
    url: jdbc:postgresql://db:5432/intershop
    username: s
    password: sa
    hikari:
      maximum-pool-size: 10
      pool-name: HikariPool-1
      idle-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        cache:
          use_second_level_cache: false
          use_query_cache: false

  sql:
    init:
      mode: always

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  logging:
    level:
      org.hibernate.SQL: DEBUG
      org.hibernate.type: TRACE
      org.springframework.web: DEBUG

  cache:
    type: simple

  session:
    timeout: 30m

  security:
    csrf:
      enabled: false

  thymeleaf:
    cache: false

---
# Dev профиль
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://db:5432/intershop_dev
    username: dev_user
    password: dev_password
  jpa:
    properties:
      hibernate:
        generate_statistics: true

---
# Prod профиль
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://db:5432/intershop_prod
    username: prod_user
    password: prod_password
  logging:
    level:
      root: INFO
      org.springframework.web: INFO
  security:
    csrf:
      enabled: true
  jpa:
    properties:
      hibernate:
        generate_statistics: false