spring:
  application:
    name: intershop
  main:
    banner-mode: off

  r2dbc:
    url: r2dbc:h2:mem:///intershop;DB_CLOSE_DELAY=-1
    username: sa
    password: 
    pool:
      max-size: 10
      initial-size: 5
      max-idle-time: 30s

  data:
    r2dbc:
      repositories:
        enabled: true

  sql:
    init:
      mode: always

  codec:
    max-in-memory-size: 50MB

  logging:
    level:
      org.springframework.r2dbc: DEBUG
      org.springframework.web: DEBUG
      io.r2dbc: DEBUG

  cache:
    type: simple

  thymeleaf:
    cache: false
    reactive:
      max-chunk-size: 8192
    check-template-location: true

  session:
    timeout: 30m

  security:
    csrf:
      enabled: false

  web:
    resources:
      add-mappings: true

  lifecycle:
    timeout-per-shutdown-phase: 15s

---
spring:
  config:
    activate:
      on-profile: dev
  r2dbc:
    url: r2dbc:h2:mem:///intershop_dev;DB_CLOSE_DELAY=-1
    username: sa
    password: 
  logging:
    level:
      io.r2dbc: DEBUG

---
spring:
  config:
    activate:
      on-profile: prod
  r2dbc:
    url: r2dbc:h2:mem:///intershop_prod;DB_CLOSE_DELAY=-1
    username: sa
    password: 
  logging:
    level:
      root: INFO
      org.springframework.web: INFO
  thymeleaf:
    cache: true
  security:
    csrf:
      enabled: true