server:
  port:   8081

spring:
  application:
    name: payment-service
  main:
    banner-mode: off
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081
          jwk-set-uri: http://localhost:8081/oauth2/jwks

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui-custom.html
    tryItOutEnabled: true
    persistAuthorization: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

---
spring:
  config:
    activate:
      on-profile: dev
  logging:
    level:
      org.springframework.web: DEBUG
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081
          jwk-set-uri: http://localhost:8081/oauth2/jwks

---
spring:
  config:
    activate:
      on-profile: prod
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH2_ISSUER_URI:http://payment-service:8081}
          jwk-set-uri: ${OAUTH2_JWK_SET_URI:http://payment-service:8081/oauth2/jwks}