spring:
  application:
    name: intershop
  main:
    banner-mode: off

  r2dbc:
    url: r2dbc:h2:mem:///intershop;DB_CLOSE_DELAY=-1
    username: sa
    password: 
    pool:
      max-size: 10
      initial-size: 5
      max-idle-time: 30s

  data:
    r2dbc:
      repositories:
        enabled: true
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 2000
      connect-timeout: 2000

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

  codec:
    max-in-memory-size: 50MB

  logging:
    level:
      org.springframework.r2dbc: DEBUG
      org.springframework.web: DEBUG
      io.r2dbc: DEBUG

  cache:
    type: redis
    redis:
      time-to-live: 3600000
      cache-null-values: false

  thymeleaf:
    cache: false
    reactive:
      max-chunk-size: 8192
    check-template-location: true

  session:
    timeout: 30m

  web:
    resources:
      add-mappings: true

  lifecycle:
    timeout-per-shutdown-phase: 15s

  security:
    oauth2:
      client:
        registration:
          payment-client:
            client-id: intershop-client
            client-secret: secret
            authorization-grant-type: client_credentials
            scope: payment_api
        provider:
          payment-provider:
            token-uri: http://localhost:8081/oauth2/token

payment:
  service:
    url: http://localhost:8081
    connect-timeout: 5000
    read-timeout: 5000
    write-timeout: 5000
    max-in-memory-size: 10MB

cache:
  item:
    ttl: 120
    detail-prefix: "item:detail:"
    list-prefix: "item:list:" #
    search-prefix: "item:search:"

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

---
spring:
  config:
    activate:
      on-profile: dev
  r2dbc:
    url: r2dbc:h2:mem:///intershop_dev;DB_CLOSE_DELAY=-1
    username: sa
    password: 
  logging:
    level:
      io.r2dbc: DEBUG
  data:
    redis:
      host: localhost
      port: 6379

payment:
  service:
    url: http://localhost:9090

---
spring:
  config:
    activate:
      on-profile: prod
  r2dbc:
    url: ${SPRING_R2DBC_URL:r2dbc:postgresql://db:5432/intershop}
    username: ${SPRING_R2DBC_USERNAME:s}
    password: ${SPRING_R2DBC_PASSWORD:sa}
  logging:
    level:
      root: INFO
      org.springframework.web: INFO
  thymeleaf:
    cache: true
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:redis}
      port: ${SPRING_DATA_REDIS_PORT:6379}
  security:
    oauth2:
      client:
        registration:
          payment-client:
            client-id: ${OAUTH2_CLIENT_ID:intershop-client}
            client-secret: ${OAUTH2_CLIENT_SECRET:secret}
        provider:
          payment-provider:
            token-uri: ${OAUTH2_TOKEN_URI:http://payment-service:8081/oauth2/token}

payment:
  service:
    url: http://payment-service:8081